# Generated by Django 5.1.6 on 2025-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawledPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="WebPage",
        ),
    ]
